#!/bin/sh
# Auterion RC Mapping
#
# This script contains the basic Auterion RC configuration.
#

# RC channel mapping
param set RC_MAP_THROTTLE 1
param set RC_MAP_ROLL 2
param set RC_MAP_PITCH 3
param set RC_MAP_YAW 4
param set RC_MAP_FLTMODE 5
param set RC_MAP_KILL_SW 6
param set RC_MAP_TRANS_SW 7
param set RC_MAP_AUX1 8

# Flight modes
param set COM_FLTMODE1 2
param set COM_FLTMODE4 1
param set COM_FLTMODE6 5
