#!/bin/sh
#
# Auterion Base
#
# This script contains all the defaults for our internal vehicles.
#
# The critical parameters are
# MPC_POS_MODE to enable jerk limited multicopter position control
# MAV_1_CONFIG and SER_TEL2_BAUD to enable mavlink on companion link (TELEM2)
#

# Position Mode Tuning
param set MPC_POS_MODE 3
param set MPC_ACC_DOWN_MAX 1.0000
param set MPC_ACC_UP_MAX 2.0000
param set MPC_ACC_HOR 3.000
param set MPC_ACC_HOR_MAX 3.000
param set MPC_JERK_MIN 15.0000
param set MPC_JERK_MAX 20.0000
param set MPC_VEL_MANUAL 6.0
param set MPC_XY_TRAJ_P 1.0000

# MAVLink Parameters
param set MAV_0_CONFIG 101
param set MAV_0_FORWARD 1
param set MAV_0_MODE 0
param set MAV_0_RATE 1200
param set MAV_1_CONFIG 102
param set MAV_1_FORWARD 1
param set MAV_1_MODE 2
param set MAV_1_RATE 100000
param set SER_TEL1_BAUD 57600
param set SER_TEL2_BAUD 1500000

# RTL Parameters
param set RTL_DESCEND_ALT 10.0000
param set RTL_LAND_DELAY 0.0000
param set RTL_RETURN_ALT 30.0000

# Logger Parameters
param set SDLOG_DIRS_MAX 20

# Power Parametets
param set BAT_CRIT_THR 0.35
param set BAT_EMERGEN_THR 0.10
param set BAT_LOW_THR 0.40

# Circuit breakers
param set CBRK_IO_SAFETY 22027

# Commander Parameters
param set COM_DISARM_LAND 1

# RC mapping
param set RC_MAP_THROTTLE 1
param set RC_MAP_ROLL 2
param set RC_MAP_PITCH 3
param set RC_MAP_YAW 4
param set RC_MAP_FLTMODE 5
param set COM_FLTMODE1 2
param set COM_FLTMODE4 1
#leaving out the last flight mode such that it's possible to map manual mode if needed
#param set COM_FLTMODE6 5
param set RC_MAP_KILL_SW 6
param set RC_MAP_TRANS_SW 7
param set RC_MAP_AUX1 8
